#!/bin/sh -e

#DEBHELPER#

if [ "$1" = "configure" ]; then
  ldconfig;
fi

if [ "$(dpkg --print-architecture)" = armhf ]; then
  ln -s /lib/ld-linux-armhf.so.3 /lib/ld-linux.so.3 2>/dev/null || true
fi

if ! [ -e /etc/asound.conf ]; then
  printf "No existing /etc/asound.conf, creating one with preferred config\n"
  cat <<\EOF > /etc/asound.conf
pcm.mmap0 {
    type mmap_emul;
    slave {
      pcm "hw:0,0";
    }
}

pcm.!default {
  type plug;
  slave {
    pcm mmap0;
  }
}
EOF
fi
